In [1]:
# Let's see what we have  before we start working  on the data

In [2]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('data.csv')

In [6]:
df.head()

,id,total_quantity,Availability,featured_image,product_name,price,Discount,model_Name,Description,Category,slug,shipping_fee
0,NaN,100,70,NaN,solid cotton blend collar neck womens a-line d...,1699,50,life,"Size:Large,Medium,Small,X-Large,X-Small",Westernwear-Women,solid-cotton-blend-collar-neck-womens-a-line-d...,400
1,NaN,100,70,NaN,polyester peter pan collar womens blouson dres...,3499,30,only,"Size:34,36,38,40",Westernwear-Women,polyester-peter-pan-collar-womens-blouson-dres...,400
2,NaN,100,70,NaN,solid polyester blend wide neck womens regular...,1199,50,fratini,"Size:Large,X-Large,XX-Large",Westernwear-Women,solid-polyester-blend-wide-neck-womens-regular...,400
3,NaN,100,70,NaN,stripes polyester sweetheart neck womens dress...,2299,40,zink london,"Size:Large,Medium,Small,X-Large",Westernwear-Women,stripes-polyester-sweetheart-neck-womens-dress...,400
4,NaN,100,70,NaN,regular fit regular length denim womens jeans ...,1699,50,life,"Size:26,28,30,32,34,36",Westernwear-Women,regular-fit-regular-length-denim-womens-jeans-...,400

In [8]:
df.Category.unique()

array(['Westernwear-Women', 'Indianwear-Women',
       'Lingerie&Nightwear-Women', 'Footwear-Women', 'Watches-Women'],
      dtype=object)

In [9]:
# Create a new column named Categories_id and assign a numeric value to each Category column value 1 for Westernwear-Women, 2 for Indianwear-Women, 3 for Lingere, 4 for Footwear and 5 for Watches
df.loc[df['Category'] == 'Westernwear-Women', 'Category'] = 1
df.loc[df['Category'] == 'Indianwear-Women', 'Category'] = 2
df.loc[df['Category'] == 'Lingerie&Nightwear-Women', 'Category'] = 3
df.loc[df['Category'] == 'Footwear-Women', 'Category'] = 4
df.loc[df['Category'] == 'Watches-Women', 'Category'] = 5

In [10]:
# rename the column name from Category to Categories_id
df.rename(columns={'Category': 'Categories_id'}, inplace=True)

In [11]:
df.head(2)

,total_quantity,Availability,featured_image,product_name,price,Discount,model_Name,Description,Categories_id,slug,shipping_fee
0,100,70,NaN,solid cotton blend collar neck womens a-line d...,1699,50,life,"Size:Large,Medium,Small,X-Large,X-Small",1,solid-cotton-blend-collar-neck-womens-a-line-d...,400
1,100,70,NaN,polyester peter pan collar womens blouson dres...,3499,30,only,"Size:34,36,38,40",1,polyester-peter-pan-collar-womens-blouson-dres...,400

In [12]:
df['featured_image'] = 'media/featured_image/default.jpg'

In [14]:
df['id'] = np.arange(1, len(df) + 1)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18374 entries, 0 to 18373
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   total_quantity  18374 non-null  int64
 1   Availability    18374 non-null  int64
 2   featured_image  18374 non-null  object
 3   product_name    18374 non-null  object
 4   price           18374 non-null  int64
 5   Discount        18374 non-null  int64
 6   model_Name      18374 non-null  object
 7   Description     18374 non-null  object
 8   Categories_id   18374 non-null  object
 9   slug            18374 non-null  object
 10  shipping_fee    18374 non-null  int64
 11  id              18374 non-null  int32
dtypes: int32(1), int64(5), object(6)
memory usage: 1.6+ MB

In [16]:
final_df = df[['id', 'total_quantity', 'Availability',  'product_name', 'price', 'Discount', 'model_Name', 'Description', 'Categories_id', 'slug', 'shipping_fee', 'featured_image']]

In [17]:
final_df.head(2)

,id,total_quantity,Availability,featured_image,product_name,price,Discount,model_Name,Description,Categories_id,slug,shipping_fee
0,1,100,70,media/featured_image/default.jpg,solid cotton blend collar neck womens a-line d...,1699,50,life,"Size:Large,Medium,Small,X-Large,X-Small",1,solid-cotton-blend-collar-neck-womens-a-line-d...,400
1,2,100,70,media/featured_image/default.jpg,polyester peter pan collar womens blouson dres...,3499,30,only,"Size:34,36,38,40",1,polyester-peter-pan-collar-womens-blouson-dres...,400

In [18]:
final_df.to_csv('final_data.csv', index=False)